# The opm image is expected to contain /bin/opm (with a serve subcommand) and /bin/grpc_health_probe
ARG OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.17

FROM ${OPM_IMAGE}

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

ENV PACKAGE_NAME=ptp-operator

COPY .konflux/catalog/$PACKAGE_NAME/ /configs/$PACKAGE_NAME

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

LABEL operators.operatorframework.io.index.configs.v1=/configs
