ARG BUILDER_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.25
# OCP addons/redhat/Dockerfile.ocp runtime, Konflux-pullable (registry.ci.openshift.org is not).
ARG RUNTIME_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-base-rhel9:assembly.stream

# Built with path-context "." (repo root). Sources under pkg/linuxptp-daemon/.
# Live yum on openshift-base-rhel9. OCP CI images include AppStream; Konflux
# openshift-base-rhel9 does not, so add CentOS Stream AppStream for operands.

FROM ${BUILDER_IMAGE} AS builder
USER root
WORKDIR /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon
COPY pkg/linuxptp-daemon/ .
RUN make clean && make

FROM ${RUNTIME_IMAGE}

COPY .konflux/rpms/linuxptp-daemon/centos-appstream.repo /etc/yum.repos.d/

RUN yum -y update && yum -y update glibc && yum --setopt=skip_missing_names_on_install=False -y \
  install \
  pciutils \
  linuxptp \
  ethtool \
  hwdata \
  synce4l \
  iproute \
  procps-ng \
  chrony \
  && (yum -y install gpsd-minimal gpsd-minimal-clients || yum -y install gpsd gpsd-clients) \
  && yum clean all

RUN ln -s /usr/bin/gpspipe /usr/local/bin/gpspipe
RUN ln -s /usr/sbin/gpsd /usr/local/sbin/gpsd
RUN ln -s /usr/bin/ubxtool /usr/local/bin/ubxtool

COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon/bin/ptp /usr/local/bin/
COPY pkg/linuxptp-daemon/extra/leap-seconds.list /usr/share/zoneinfo/leap-seconds.list

CMD ["/usr/local/bin/ptp"]
