ARG BUILDER_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.25
ARG RUNTIME_IMAGE=quay.io/centos/centos:stream9

# Built with path-context "." so Hermeto/cachi2 RPM injection (repo root) is
# visible to yum. Sources are copied from pkg/linuxptp-daemon/.

FROM ${BUILDER_IMAGE} AS builder
USER root
WORKDIR /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon
COPY pkg/linuxptp-daemon/ .
RUN make clean && make

FROM ${RUNTIME_IMAGE}

# Do not `yum update` here: hermetic builds only have the locked RPM set from
# .konflux/rpms/linuxptp-daemon. A full update pulls unlocked packages and fails.
RUN yum --setopt=skip_missing_names_on_install=False -y install \
      pciutils \
      linuxptp \
      ethtool \
      hwdata \
      synce4l \
      iproute \
      procps-ng \
      chrony \
      gpsd-minimal \
      gpsd-minimal-clients \
 && yum clean all

RUN ln -s /usr/bin/gpspipe /usr/local/bin/gpspipe
RUN ln -s /usr/sbin/gpsd /usr/local/sbin/gpsd
RUN ln -s /usr/bin/ubxtool /usr/local/bin/ubxtool

COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon/bin/ptp /usr/local/bin/
COPY pkg/linuxptp-daemon/extra/leap-seconds.list /usr/share/zoneinfo/leap-seconds.list

CMD ["/usr/local/bin/ptp"]
