name: "linuxptp-daemon: golangci-lint"
on:
  push:
    branches: ["main", "one-repo*", "release-*"]
    paths:
      - 'pkg/linuxptp-daemon/**'
  pull_request:
    paths:
      - 'pkg/linuxptp-daemon/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - uses: golangci/golangci-lint-action@v9
        with:
          working-directory: pkg/linuxptp-daemon
